import type { SheetComponent } from '../agent/types'

const CANVAS_W = 2480
const CANVAS_H = 1754
const PADDING = 60
const HEADER_H = 120
const FOOTER_H = 60
const LABEL_H = 36
const GAP = 24

export async function composeModelSheet(
  components: SheetComponent[],
  characterName: string,
): Promise<string> {
  const canvas = document.createElement('canvas')
  canvas.width = CANVAS_W
  canvas.height = CANVAS_H
  const ctx = canvas.getContext('2d')!

  // Background
  ctx.fillStyle = '#FAFAF8'
  ctx.fillRect(0, 0, CANVAS_W, CANVAS_H)

  // Outer border
  ctx.strokeStyle = '#1a1a1a'
  ctx.lineWidth = 6
  ctx.strokeRect(PADDING / 2, PADDING / 2, CANVAS_W - PADDING, CANVAS_H - PADDING)

  // Header bar
  ctx.fillStyle = '#1a1a1a'
  ctx.fillRect(PADDING / 2, PADDING / 2, CANVAS_W - PADDING, HEADER_H)

  // Title text
  ctx.fillStyle = '#FFFFFF'
  ctx.font = 'bold 64px Inter, system-ui, sans-serif'
  ctx.textBaseline = 'middle'
  ctx.fillText(
    characterName.toUpperCase() + ' — MODEL SHEET',
    PADDING + 20,
    PADDING / 2 + HEADER_H / 2,
  )

  // Subtitle
  ctx.font = '28px Inter, system-ui, sans-serif'
  ctx.fillStyle = '#AAAAAA'
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`
  const subtitleWidth = ctx.measureText(subtitle).width
  ctx.fillText(subtitle, CANVAS_W - PADDING - subtitleWidth - 20, PADDING / 2 + HEADER_H / 2)

  // Draw components in a grid
  const doneComponents = components.filter((c) => c.status === 'done' && c.imageData)
  if (doneComponents.length === 0) {
    return canvas.toDataURL('image/png')
  }

  const contentY = PADDING / 2 + HEADER_H + GAP
  const contentH = CANVAS_H - contentY - FOOTER_H - PADDING / 2 - GAP
  const contentW = CANVAS_W - PADDING

  const { cols, rows } = gridDimensions(doneComponents.length)
  const cellW = Math.floor((contentW - GAP * (cols - 1)) / cols)
  const cellH = Math.floor((contentH - GAP * (rows - 1) - LABEL_H * rows) / rows)

  const imageLoadPromises = doneComponents.map((comp, i) => {
    return new Promise<void>((resolve) => {
      const col = i % cols
      const row = Math.floor(i / cols)
      const x = PADDING / 2 + col * (cellW + GAP)
      const y = contentY + row * (cellH + LABEL_H + GAP)

      // Cell background
      ctx.fillStyle = '#FFFFFF'
      ctx.fillRect(x, y, cellW, cellH)

      // Cell border
      ctx.strokeStyle = '#DDDDDD'
      ctx.lineWidth = 2
      ctx.strokeRect(x, y, cellW, cellH)

      if (comp.imageData) {
        const img = new Image()
        img.onload = () => {
          // Cover-fit the image within the cell
          const { sx, sy, sw, sh } = coverFit(img.width, img.height, cellW, cellH)
          ctx.drawImage(img, sx, sy, sw, sh, x, y, cellW, cellH)

          // Label below
          ctx.fillStyle = '#1a1a1a'
          ctx.font = 'bold 24px Inter, system-ui, sans-serif'
          ctx.textBaseline = 'top'
          ctx.textAlign = 'center'
          ctx.fillText(comp.label, x + cellW / 2, y + cellH + 6)
          ctx.textAlign = 'left'
          resolve()
        }
        img.onerror = () => resolve()
        img.src = comp.imageData
      } else {
        resolve()
      }
    })
  })

  await Promise.all(imageLoadPromises)

  // Footer
  ctx.fillStyle = '#888888'
  ctx.font = '22px Inter, system-ui, sans-serif'
  ctx.textBaseline = 'bottom'
  ctx.fillText(
    'Generated by Character Model Sheet Generator — AI-powered animation reference tool',
    PADDING + 20,
    CANVAS_H - PADDING / 2 - 12,
  )

  return canvas.toDataURL('image/png')
}

function gridDimensions(count: number): { cols: number; rows: number } {
  if (count <= 2) return { cols: 2, rows: 1 }
  if (count <= 4) return { cols: 2, rows: 2 }
  if (count <= 6) return { cols: 3, rows: 2 }
  if (count <= 8) return { cols: 4, rows: 2 }
  return { cols: 4, rows: Math.ceil(count / 4) }
}

function coverFit(
  imgW: number,
  imgH: number,
  cellW: number,
  cellH: number,
): { sx: number; sy: number; sw: number; sh: number } {
  const scale = Math.max(cellW / imgW, cellH / imgH)
  const sw = cellW / scale
  const sh = cellH / scale
  const sx = (imgW - sw) / 2
  const sy = (imgH - sh) / 2
  return { sx, sy, sw, sh }
}
