import type { SheetComponent, ComponentType } from '../agent/types'

const CANVAS_W = 2480
const CANVAS_H = 1754
const PADDING = 60
const HEADER_H = 120
const FOOTER_H = 60
const GAP = 20

// Turnaround views go in the larger top row; everything else goes in the bottom row.
const TURNAROUND_TYPES: ComponentType[] = ['front_view', 'three_quarter_view', 'back_view', 'side_view']

interface CellLayout {
  comp: SheetComponent
  x: number
  y: number
  w: number
  h: number
}

export async function composeModelSheet(
  components: SheetComponent[],
  characterName: string,
): Promise<string> {
  const canvas = document.createElement('canvas')
  canvas.width = CANVAS_W
  canvas.height = CANVAS_H
  const ctx = canvas.getContext('2d')!

  // Background — pure white so it matches the white backgrounds of all generated images
  ctx.fillStyle = '#FFFFFF'
  ctx.fillRect(0, 0, CANVAS_W, CANVAS_H)

  // Outer border
  ctx.strokeStyle = '#1a1a1a'
  ctx.lineWidth = 6
  ctx.strokeRect(PADDING / 2, PADDING / 2, CANVAS_W - PADDING, CANVAS_H - PADDING)

  // Header bar
  ctx.fillStyle = '#1a1a1a'
  ctx.fillRect(PADDING / 2, PADDING / 2, CANVAS_W - PADDING, HEADER_H)

  // Title text
  ctx.fillStyle = '#FFFFFF'
  ctx.font = 'bold 64px Inter, system-ui, sans-serif'
  ctx.textBaseline = 'middle'
  ctx.fillText(
    characterName.toUpperCase() + ' — MODEL SHEET',
    PADDING + 20,
    PADDING / 2 + HEADER_H / 2,
  )

  // Subtitle
  ctx.font = '28px Inter, system-ui, sans-serif'
  ctx.fillStyle = '#AAAAAA'
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`
  const subtitleWidth = ctx.measureText(subtitle).width
  ctx.fillText(subtitle, CANVAS_W - PADDING - subtitleWidth - 20, PADDING / 2 + HEADER_H / 2)

  const doneComponents = components.filter((c) => c.status === 'done' && c.imageData)
  if (doneComponents.length === 0) {
    return canvas.toDataURL('image/png')
  }

  const contentX = PADDING / 2
  const contentY = PADDING / 2 + HEADER_H + GAP
  const contentW = CANVAS_W - PADDING
  const contentH = CANVAS_H - contentY - FOOTER_H - PADDING / 2 - GAP

  const layouts = computeLayout(doneComponents, contentX, contentY, contentW, contentH)

  const imageLoadPromises = layouts.map(({ comp, x, y, w, h }) =>
    new Promise<void>((resolve) => {
      if (comp.imageData) {
        const img = new Image()
        img.onload = () => {
          const { dx, dy, dw, dh } = containFit(img.width, img.height, w, h)
          ctx.drawImage(img, x + dx, y + dy, dw, dh)

          // Only label the color palette cell
          if (comp.type === 'color_palette') {
            ctx.fillStyle = 'rgba(26,26,26,0.7)'
            ctx.fillRect(x, y + h - 38, w, 38)
            ctx.fillStyle = '#FFFFFF'
            ctx.font = 'bold 22px Inter, system-ui, sans-serif'
            ctx.textBaseline = 'middle'
            ctx.textAlign = 'center'
            ctx.fillText(comp.label, x + w / 2, y + h - 19)
            ctx.textAlign = 'left'
          }

          resolve()
        }
        img.onerror = () => resolve()
        img.src = comp.imageData
      } else {
        resolve()
      }
    }),
  )

  await Promise.all(imageLoadPromises)

  // Footer
  ctx.fillStyle = '#888888'
  ctx.font = '22px Inter, system-ui, sans-serif'
  ctx.textBaseline = 'bottom'
  ctx.textAlign = 'left'
  ctx.fillText(
    'Generated by Character Model Sheet Generator — AI-powered animation reference tool',
    PADDING + 20,
    CANVAS_H - PADDING / 2 - 12,
  )

  return canvas.toDataURL('image/png')
}

function computeLayout(
  components: SheetComponent[],
  contentX: number,
  contentY: number,
  contentW: number,
  contentH: number,
): CellLayout[] {
  const turnarounds = components.filter((c) => TURNAROUND_TYPES.includes(c.type))
  const details = components.filter((c) => !TURNAROUND_TYPES.includes(c.type))

  // Both groups present → hierarchical two-row layout
  if (turnarounds.length > 0 && details.length > 0) {
    const topH = Math.floor(contentH * 0.62)
    const bottomH = contentH - topH - GAP

    return [
      ...rowLayout(turnarounds, contentX, contentY, contentW, topH),
      ...rowLayout(details, contentX, contentY + topH + GAP, contentW, bottomH),
    ]
  }

  // Only one group → single row spanning full height
  const all = turnarounds.length > 0 ? turnarounds : details
  return rowLayout(all, contentX, contentY, contentW, contentH)
}

function rowLayout(
  components: SheetComponent[],
  x: number,
  y: number,
  totalW: number,
  h: number,
): CellLayout[] {
  const n = components.length
  const cellW = Math.floor((totalW - GAP * (n - 1)) / n)
  return components.map((comp, i) => ({
    comp,
    x: x + i * (cellW + GAP),
    y,
    w: cellW,
    h,
  }))
}

/** Scale image to fit inside cellW×cellH, centred, no cropping. */
function containFit(
  imgW: number,
  imgH: number,
  cellW: number,
  cellH: number,
): { dx: number; dy: number; dw: number; dh: number } {
  const scale = Math.min(cellW / imgW, cellH / imgH)
  const dw = Math.floor(imgW * scale)
  const dh = Math.floor(imgH * scale)
  const dx = Math.floor((cellW - dw) / 2)
  const dy = Math.floor((cellH - dh) / 2)
  return { dx, dy, dw, dh }
}
